#!/bin/sh
CUR_DIR=$(pwd)
SAVEIFS=$IFS
IFS=$(echo -en "\n\b")

if [ -n "$1" ]; then
	wtype="$1";
else 
	wtype=$(shuf -n1 inc/types);
fi

printf "+%-41s+\n" "-----------------------------------------"
printf "|%-41s|\n" "      PicACard : Your Random Card     "
printf "|%-41s|\n" "       workout generator ($wtype)         "
printf "+%-41s+\n" "-----------------------------------------"

a=( $(cat $CUR_DIR/inc/cards ) )  
b=( $(shuf -n4 $CUR_DIR/inc/$wtype  ) )

for ((i=0;i<${#a[@]};++i)); do
	printf "|%3s %-15s %1s %15s %3s|\n" " " "${a[i]}" "=" "${b[i]}" ""
done

printf "+%-41s+\n" "-----------------------------------------"
printf "|%3s %-15s %1s %15s %3s|\n" "" "Number Card" "=" "# of Reps" ""
printf "|%3s %-15s %1s %15s %3s|\n" "" "Jacks" "=" "20 KB swings" ""
printf "|%3s %-15s %1s %15s %3s|\n" "" "Queens" "=" "6 inches (30s)" ""
printf "|%3s %-15s %1s %15s %3s|\n" "" "Kings" "=" "100 crunches" ""
printf "|%3s %-15s %1s %15s %3s|\n" "" "Aces" "=" "Planks (30s)" ""
printf "+%-41s+\n" "-----------------------------------------"
printf "|%-41s|\n" "   Drawing two cards of same suit back   "
printf "|%-41s|\n" "   to back doubles the number of reps    "
printf "+%-41s+\n" "-----------------------------------------"

IFS=$SAVEIFS
