#!/bin/sh

wtype=$(shuf -n1 inc/types)

#echo -e "+====================================+"
#echo -e "|    PicACard - Your Random Card     |"
#echo -e "|         workout generator.         |"
#echo -e "+====================================+"
#echo -e "|      Today's workout:   $wtype       |"
#echo -e "+------------------------------------+"

printf 
a=( $(cat inc/cards ) )  
b=( $(shuf -n4 inc/$wtype  ) )

for ((i=0;i<${#a[@]};++i)); do
    echo -e "     ${a[i]} \t:  ${b[i]}           "
done

echo -e "+------------------------------------+"
echo -e "| Number Card   =  # of Reps         |"
echo -e "|       Jacks   =  20 KB swing p/arm |"
echo -e "|      Queens   =  6 inches (30s)    |"
echo -e "|       Kings   =  100 crunches      |"
echo -e "|        Aces   =  Planks (30s)      |"
echo -e "+------------------------------------+"
echo -e "| Draw two cards of same suit in a   |"
echo -e "|  row doubles the number of reps.   |"
echo -e "+------------------------------------+"

